[[pages]]
path = "home.py"
name = "InÃ­cio"
icon = "ğŸ§™â€â™‚ï¸"

[[pages]]
path = "pages/perfil.py"
name = "Seu Perfil"
icon = "ğŸ†"

[[pages]]
path = "pages/pdi.py"
name = "Monte o PDI"
icon = "ğŸ“"

[[pages]]
path = "pages/trilhas.py"
name = "Trilhas de Estudos"
icon = "ğŸ“š"


[[pages]]
name = "ConteÃºdo por Ano"
icon = "ğŸ—“ï¸"
is_section = true

[[pages]]
name = "2024"
path = "pages/material_2024.py"

[[pages]]
name = "2025"
path = "pages/material_2025.py"